### ISSUE TITLE
StringUtils: ocurrencias

### ISSUE THREAD

**Issue by SergioAC52** [SergioAC52/DAM-Entornos-P3-Sergio#19]
Método Privado [estático ](https://tutorialesprogramacionya.com/javaya/detalleconcepto.php?codigo=143)de la clase de StringUtils.

El método debe tomar un String y un char. Debe devolver un entero con el numero de veces que se encuentra ese caracter en la string.

Incluir un ejemplo del metodo en el main de la misma clase.

**Comment by TilinExe816** [comment]
hecho
