### ISSUE TITLE
ArrayUtils: Calcular media

### ISSUE THREAD

**Issue by SergioAC52** [SergioAC52/DAM-Entornos-P3-Sergio#5]
Método [estático ](https://tutorialesprogramacionya.com/javaya/detalleconcepto.php?codigo=143)de la clase de ArrayUtils.

El método debe tomar un array de enteros y devolver la [media](https://enciclopediaeconomica.com/media-aritmetica/) del array como un entero.

Incluir un ejemplo del metodo en la misma clase.

**Comment by costin132** [comment]
comprobar el metodo para el merge

**Comment by SergioAC52** [comment]
Comprobado, puedes hacer el merge.
