### ISSUE TITLE
Decimales: Eliminar decimales al numero

### ISSUE THREAD

**Issue by SergioAC52** [SergioAC52/DAM-Entornos-P3-Sergio#8]
Método [estático ](https://tutorialesprogramacionya.com/javaya/detalleconcepto.php?codigo=143)de la clase de Decimales.

El método debe tomar un float y devolver la parte entera (como entero).

Incluir un ejemplo del metodo en la misma clase.

**Comment by costin132** [comment]
Comprobar el metodo, si esta bien o no

**Comment by SergioAC52** [comment]
Comprobado, puedes hacer el merge.
