### ISSUE TITLE
Decimales: Ecuación de segundo grado

### ISSUE THREAD

**Issue by SergioAC52** [SergioAC52/DAM-Entornos-P3-Sergio#9]
Método [estático ](https://tutorialesprogramacionya.com/javaya/detalleconcepto.php?codigo=143)de la clase de Decimales.

Este metodo toma tres floats como entrada: coeficienteA, coeficienteB, coeficienteC
Ejecutar la ecuacion de segundo grado y devolver en un array de floats la dos posibles soluciones

Incluir un ejemplo del metodo en la misma clase.

**Comment by costin132** [comment]
Comprobar el metodo, si esta bien o no

**Comment by SergioAC52** [comment]
Comprobado, puedes hacer el merge.
